fun main(){
    print("EN NO:")
    var a= readln()
    print("Name:")
    var b= readln()
    print("Branch:")
    var c=readln()
    print("Class:")
    var d=readln()
    print("Collage:")
    var e=readln()
    print("University:")
    var f=readln()
    print("Age:")
    var g= readln()

    println("**********")
    println("Student's data\n")
    println("En no:$a")
    println("Name:$b")
    println("Brnch:$c")
    println("Class:$d")
    println("Collage:$e")
    println("University:$f")
    println("Age:$g")
}
